# --- NOME E DESCRIÇÃO ATUALIZADOS ---
name: chef_express
description: "Chef Express: O seu assistente de cozinha inteligente para descobrir receitas com os ingredientes que você já tem em casa."
publish_to: 'none'

# A versão do seu aplicativo, pronta para o primeiro lançamento.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Atualizado para um range mais flexível

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Versão atualizada
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
